<a href="https://colab.research.google.com/github/rajat10-01/machine-learning/blob/master/HelloWorld.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
import tensorflow as tf
%tensorflow_version 2.x

In [0]:
from tensorflow import keras

In [0]:
from __future__ import absolute_import, division, print_function, unicode_literals

In [0]:
model = tf.keras.Sequential()

In [0]:
x = np.array([1, 0.2, 0.4, 0.9, 1, 0, 0.6, 0.3])

In [0]:
x_t = x.transpose()

In [0]:
w = np.array([[-0.05, 0.1, 0.1, 0.2, 0.35, 0.6, -0.9, -0.1],[-0.5, 0.1, 0.1, 0.02, 0.3, 0.36, 0.9, 0.1],[-0.05, 0.1, 0.1, 0.2, 0.35, 0.6, 0.9, -0.1],[-0.5, 0.1, 0.1, 0.02, 0.3, 0.36, -0.9, 0.1]])


In [0]:
w

array([[-0.05,  0.1 ,  0.1 ,  0.2 ,  0.35,  0.6 , -0.9 , -0.1 ],
       [-0.5 ,  0.1 ,  0.1 ,  0.02,  0.3 ,  0.36,  0.9 ,  0.1 ],
       [-0.05,  0.1 ,  0.1 ,  0.2 ,  0.35,  0.6 ,  0.9 , -0.1 ],
       [-0.5 ,  0.1 ,  0.1 ,  0.02,  0.3 ,  0.36, -0.9 ,  0.1 ]])

In [0]:
y = np.matmul(w, x_t)

In [0]:
y.shape

(4,)

In [0]:
y

array([-0.03 ,  0.448,  1.05 , -0.632])

In [0]:
b= np.array([-0.8,-0.1,-0.1,-0.1])

In [0]:
b.shape

(4,)

In [0]:
y_ = np.add(y,b)

In [0]:
y_

array([-0.83 ,  0.348,  0.95 , -0.732])

In [0]:
y_t = y_.transpose()

In [0]:
n_y = np.matmul(np.array([-0.05, 0.1, 0.1, 0.2]), y_t)

In [0]:
n_y

0.024900000000000033

In [0]:
y_t.shape

(4,)